[project]
name = "beorg2journelly"
version = "0.1.0"
description = "Two-way synchronization of TODO tasks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-lsp-server>=1.13.1",
]
